---
title: "Testbed output analysis"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Import libraries:

```{r}
library(jsonlite)
library(tidyverse)
library(scales)
library(ggnewscale)
library(here)
```

Load the data:

```{r}
expname = 'hspa+_h3'
filename = paste0('experiment_', expname, '.json')
path = here() %>% str_remove('analysis') %>% paste0('client/out/', filename)
df <- fromJSON(readLines(path), flatten=TRUE) %>% as.data.frame
print(df)
```

Prepare data for plotting:

```{r}
config_updates = df %>% filter(type == 'LINK_CONFIG_UPDATE')
status = df %>% filter(type == 'STATUS')
buffer_empty_events = df %>% filter(type=='BUFFER_EMPTY')
buffer_loaded_events = df %>% filter(type=='BUFFER_LOADED')
rep_switch_events = df %>% filter(type=='REPRESENTATION_SWITCH')
```

```{r}
playback_events = df %>% filter(type=='PLAYBACK_STALLED' | type=='PLAYBACK_RESUMED') %>% select(timestamp, type)

stalled_areas = data.frame()
stalled_start = 0
stalled = FALSE
for (i in 1:nrow(playback_events)) {
  if (!stalled) {
    if (playback_events[i,]$type == 'PLAYBACK_STALLED') {
      stalled_start = playback_events[i,]$timestamp
      stalled = TRUE
    }
  }
  else {
    stalled_end = playback_events[i,]$timestamp
    stalled_areas <- rbind(stalled_areas, data.frame(start=stalled_start, end=stalled_end))
    stalled = FALSE
  }
}
```

Number of stalled events: `r nrow(stalled_areas)`.

```{r}
stall_durations = stalled_areas$end - stalled_areas$start
summary(stall_durations)
stall_duration = sum(stall_durations)
```

Total stall duration: `r stall_duration`.

Buffer health plot:

```{r}
scaleFactor <- max(config_updates$data.bw) / max(status$data.videoBuffer) * 3

ggplot() +
  # Bandwidth
  geom_area(data=config_updates, aes(x=timestamp, y=data.bw/scaleFactor, color='Bandwidth'), linetype='dashed', alpha=0.15) +
  scale_color_manual(
    name='',
    values=c('Bandwidth'='gray')
  ) +
  new_scale_color() +
  # Media bitrate
  geom_step(data=rep_switch_events, aes(x=timestamp, y=(data.videoBitrate + data.audioBitrate)/1000/scaleFactor, color='Media bitrate'), linetype='dashed') +
  scale_color_manual(
    name='',
    values=c('Media bitrate'='orange')
  ) +
  new_scale_color() +
  # Buffer size AUDIO
  geom_step(data=status, aes(x=timestamp, y=data.audioBuffer, color='Buffer size (audio)'), alpha=0.5) +
  # Buffer size VIDEO
  geom_step(data=status, aes(x=timestamp, y=data.videoBuffer, color='Buffer size (video)')) +
  # Stalled areas
  geom_rect(data=stalled_areas, aes(xmin=start, xmax=end, ymin=0, ymax=Inf, fill='Playback stalled'), alpha=0.15) +
  scale_color_manual(
    name='',
    values=c(
      'Buffer size (video)'='black',
      'Buffer size (audio)'='darkorchid'
    )
  ) +
  new_scale_color() +
  # Buffer empty line
  geom_vline(data=buffer_empty_events, aes(xintercept=timestamp, color='Buffer empty'), linetype='dashed', alpha=0.25) +
  # Buffer loaded line
  geom_vline(data=buffer_loaded_events, aes(xintercept=timestamp, color='Buffer loaded'), linetype='dashed', alpha=0.25) +
  scale_color_manual(
    name='',
    values = c(
      'Buffer empty'='red',
      'Buffer loaded'='green4'
    )
  ) +
  scale_fill_manual(
    name='',
    values = c('Playback stalled'='red')
  ) +
  labs(
    x='Time',
    y='Seconds',
    title=filename
  ) +
  theme_bw() +
  theme(
    legend.position = 'bottom',
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  scale_x_continuous(
    breaks=seq(0,max(config_updates$timestamp),10)
  ) +
  scale_y_continuous(
    sec.axis = sec_axis(~ . * scaleFactor, name = "Mbps", breaks=seq(0, max(config_updates$data.bw), 2))
  )
```

Live latency plot:

```{r}
ggplot() +
  # Live latency
  geom_line(data=status, aes(x=timestamp, y=data.latency, color='Live latency'), size=0.75) +
  # Playback rate
  geom_line(data=status, aes(x=timestamp, y=data.rate, color='Playback rate'), size=0.5) +
  scale_color_manual(name='', values=c('Live latency'='black', 'Playback rate'='red')) +
  # Stalled areas
  geom_rect(data=stalled_areas, aes(xmin=start, xmax=end, ymin=0, ymax=Inf, fill='Playback stalled'), alpha=0.15) +
  scale_fill_manual(
    name='',
    values = c('Playback stalled'='red')
  ) +
  new_scale_color() +
  # Buffer empty line
  geom_vline(data=buffer_empty_events, aes(xintercept=timestamp, color='Buffer empty'), linetype='dashed', alpha=0.25) +
  # Buffer loaded line
  geom_vline(data=buffer_loaded_events, aes(xintercept=timestamp, color='Buffer loaded'), linetype='dashed', alpha=0.25) +
  scale_color_manual(
    name='',
    values = c(
      'Buffer empty'='red',
      'Buffer loaded'='green4'
    )
  ) +
  labs(
    x='Time (s)',
    y='Live latency (s)',
    title=paste0('Live latency: ', filename)
  ) +
  theme_bw() +
  theme(
    legend.position = 'bottom',
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  scale_x_continuous(
    breaks=seq(0, max(status$timestamp), 10)
  ) +
  scale_y_continuous(
    breaks=seq(0, ceiling(max(status$data.latency, na.rm=TRUE)), 1)
  )
```


Fragment waterfall.

```{r}
library(lubridate)

fragment_load = df %>%
  filter(type == 'FRAGMENT_LOADED') %>%
  mutate(
    data.requestStartDate=ymd_hms(data.requestStartDate),
    data.requestEndDate=ymd_hms(data.requestEndDate),
    requestDuration=as.numeric(data.requestEndDate-data.requestStartDate),
    requestOffset=as.numeric(data.requestStartDate-min(data.requestStartDate)),
    id=seq_along(data.url)
  )

fragment_load
```

```{r}
vo = fragment_load %>% #filter(data.mediaType == 'video') %>%
  mutate(fn=str_extract(data.url, 'chunk-.+'))

ggplot() +
  geom_rect(
    data=fragment_load,
    aes(xmin=id, xmax=id+0.5, ymin=requestOffset, ymax=requestOffset+requestDuration, fill=data.mediaType)
  ) +
  geom_text(
    data = vo,
    aes(y=requestOffset+requestDuration, x=id, label=fn, hjust=-0.1, vjust=0.85),
    size=2
  ) +
  coord_flip() +
  scale_x_reverse() +
  labs(
    y = 'Time (s)',
    x = '',
    title = paste0('Waterfall: ', filename),
    fill = ''
  ) +
  theme_minimal() +
  theme(
    legend.position = 'bottom',
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
  )
```

